// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formBtn': string;
  'forms': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
