// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'best': string;
  'btn': string;
  'content': string;
  'hide': string;
  'letter': string;
  'letters': string;
  'not_hide': string;
}
export const cssExports: CssExports;
export default cssExports;
