// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bur_rev': string;
  'content': string;
  'data': string;
  'field_rev': string;
  'fio': string;
  'greeting': string;
  'letter_chosen': string;
  'letter_not_chosen': string;
  'letters': string;
  'main_content': string;
  'persons': string;
  'persons_hide': string;
  'rate_teacher': string;
  'rate_teacher_button': string;
  'rate_teacher_fields': string;
  'review_hide': string;
  'review_show': string;
  'showHide': string;
  'teacher': string;
}
export const cssExports: CssExports;
export default cssExports;
