// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'best': string;
  'btn': string;
  'content': string;
  'fio': string;
  'greeting': string;
  'letter_chosen': string;
  'letter_not_chosen': string;
  'letters': string;
  'main_content': string;
  'persons': string;
  'persons_hide': string;
  'review_hide': string;
  'review_show': string;
  'showHide': string;
  'teacher': string;
  'worst': string;
}
export const cssExports: CssExports;
export default cssExports;
