// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check': string;
  'checkcross': string;
  'toggle': string;
  'toggle-item': string;
}
export const cssExports: CssExports;
export default cssExports;
