// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'around_inp': string;
  'content': string;
  'greeting': string;
  'inp': string;
  'register': string;
}
export const cssExports: CssExports;
export default cssExports;
