// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'fields': string;
  'greeting': string;
  'register': string;
}
export const cssExports: CssExports;
export default cssExports;
