// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'biggrid': string;
  'greeting': string;
  'grid': string;
  'news_full': string;
  'news_text_hidden': string;
  'news_text_shown': string;
  'news_title_chosen': string;
  'news_title_unchosen': string;
  'textfields': string;
}
export const cssExports: CssExports;
export default cssExports;
