// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'css-modalDialog': string;
  'fadeIn': string;
  'fadeOut': string;
  'modal': string;
  'modalDialog': string;
  'modalFadeOut': string;
  'modalMain': string;
  'name': string;
  'slideIn': string;
  'slideOut': string;
  'smalltext': string;
}
export const cssExports: CssExports;
export default cssExports;
